# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import os
import re
def partition_list():
    regex = r"([^\\s]*:)"
    driver = os.popen("wmic logicaldisk get name").read()
    drives = re.findall(regex, driver)

    partition_list = [partition.strip() for drive in drives for partition in drive.split(":") if partition.strip()]
    partition_list[0] = partition_list[0].strip("Name  \n\n")
    return partition_list

class Ui_Drive(object):
    def setupUi(self, Drive):
        Drive.setObjectName("Drive")
        Drive.resize(744, 533)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.comboBox = QtWidgets.QComboBox(parent=self.dockWidgetContents)
        self.comboBox.setGeometry(QtCore.QRect(10, 10, 631, 31))
        self.comboBox.setObjectName("comboBox")
        self.scan_button = QtWidgets.QPushButton(parent=self.dockWidgetContents)
        self.scan_button.setGeometry(QtCore.QRect(650, 10, 71, 41))
        self.scan_button.setObjectName("scan_button")
        self.scan_button.clicked.connect(self.button_click)
        Drive.setWidget(self.dockWidgetContents)

        self.retranslateUi(Drive)
        QtCore.QMetaObject.connectSlotsByName(Drive)
        self.comboBox.addItem("Select your drive")
        list = partition_list()
        self.comboBox.addItems(list)
    def retranslateUi(self, Drive):
        _translate = QtCore.QCoreApplication.translate
        Drive.setWindowTitle(_translate("Drive", "DockWidget"))
        self.scan_button.setText(_translate("Drive", "scan"))
    def button_click(self):
        selected_drive = self.comboBox.currentText()
        print(selected_drive)
        pass

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Drive = QtWidgets.QDockWidget()
    ui = Ui_Drive()
    ui.setupUi(Drive)
    Drive.show()
    sys.exit(app.exec())
